default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: beautycollection_development

test:
  <<: *default
  database: beautycollection_test

production:
  <<: *default
  database: beautycollection_production
  username: beautycollection
  password: <%= ENV['BEAUTYCOLLECTION_DATABASE_PASSWORD'] %>
